### ISSUE TITLE
Give the option to configure timeout

### ISSUE THREAD

**Issue by jvillarejo** [cyx/requests#4]
I'm really comfortable with the abstraction provided by this Request gem.  

The problem right now is that I want to implement a short circuit an retry after a certain time interval, but I'm not able to pass read_timeout to the Net::HTTP.start method 

What do you think about this?

**Comment by cyx** [comment]
I think it's a great idea. Let me see if I can spin up a PR around it.

**Comment by cyx** [comment]
I just addressed and merged. Will release a new gem shortly.

**Comment by cyx** [comment]
1.0.1 version should be released: https://rubygems.org/gems/requests/versions/1.0.1
